new TradingView.widget(
    {
        "autosize":true,
        "symbol":"BINANCE:BTCUSDT",
        "interval":"240",
        "timezzone":"Etc/Utc",
        "theme":"light",
        "style":"1",
        "locale":"en",
        "toolbar_bg":"#f1f3f6",
        "enable_publishing":false,
        "withdaterages":true,
        "hide_side_toolbar":false,
        "allow_smybol_change":false,
        "watchlist":[
            "BINANCE:BTCUSDT",
            "BINANCE:ETHUSDT"
        ],
        "details":true,
        "hotlist":true,
        "calender":true,
        "studies":[
            "STD;SMA"
        ],
        "container_id":"chart",
        "show_popup_button":true,
        "popup_width":"1000",
        "popup_height":"650"

    }
);